// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	imagegen "github.com/sushistack/yt.pipe/internal/plugin/imagegen"
)

// MockImageGen is an autogenerated mock type for the ImageGen type
type MockImageGen struct {
	mock.Mock
}

type MockImageGen_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageGen) EXPECT() *MockImageGen_Expecter {
	return &MockImageGen_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, prompt, opts
func (_m *MockImageGen) Generate(ctx context.Context, prompt string, opts imagegen.GenerateOptions) (*imagegen.ImageResult, error) {
	ret := _m.Called(ctx, prompt, opts)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 *imagegen.ImageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, imagegen.GenerateOptions) (*imagegen.ImageResult, error)); ok {
		return rf(ctx, prompt, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, imagegen.GenerateOptions) *imagegen.ImageResult); ok {
		r0 = rf(ctx, prompt, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imagegen.ImageResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, imagegen.GenerateOptions) error); ok {
		r1 = rf(ctx, prompt, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageGen_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockImageGen_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - opts imagegen.GenerateOptions
func (_e *MockImageGen_Expecter) Generate(ctx interface{}, prompt interface{}, opts interface{}) *MockImageGen_Generate_Call {
	return &MockImageGen_Generate_Call{Call: _e.mock.On("Generate", ctx, prompt, opts)}
}

func (_c *MockImageGen_Generate_Call) Run(run func(ctx context.Context, prompt string, opts imagegen.GenerateOptions)) *MockImageGen_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(imagegen.GenerateOptions))
	})
	return _c
}

func (_c *MockImageGen_Generate_Call) Return(_a0 *imagegen.ImageResult, _a1 error) *MockImageGen_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageGen_Generate_Call) RunAndReturn(run func(context.Context, string, imagegen.GenerateOptions) (*imagegen.ImageResult, error)) *MockImageGen_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: ctx, sourceImage, prompt, opts
func (_m *MockImageGen) Edit(ctx context.Context, sourceImage []byte, prompt string, opts imagegen.EditOptions) (*imagegen.ImageResult, error) {
	ret := _m.Called(ctx, sourceImage, prompt, opts)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 *imagegen.ImageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, imagegen.EditOptions) (*imagegen.ImageResult, error)); ok {
		return rf(ctx, sourceImage, prompt, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, imagegen.EditOptions) *imagegen.ImageResult); ok {
		r0 = rf(ctx, sourceImage, prompt, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imagegen.ImageResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, imagegen.EditOptions) error); ok {
		r1 = rf(ctx, sourceImage, prompt, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockImageGen creates a new instance of MockImageGen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageGen(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageGen {
	mock := &MockImageGen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
