// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	output "github.com/sushistack/yt.pipe/internal/plugin/output"
)

// MockAssembler is an autogenerated mock type for the Assembler type
type MockAssembler struct {
	mock.Mock
}

type MockAssembler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssembler) EXPECT() *MockAssembler_Expecter {
	return &MockAssembler_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function with given fields: ctx, input
func (_m *MockAssembler) Assemble(ctx context.Context, input output.AssembleInput) (*output.AssembleResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 *output.AssembleResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, output.AssembleInput) (*output.AssembleResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, output.AssembleInput) *output.AssembleResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.AssembleResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, output.AssembleInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAssembler_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type MockAssembler_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - ctx context.Context
//   - input output.AssembleInput
func (_e *MockAssembler_Expecter) Assemble(ctx interface{}, input interface{}) *MockAssembler_Assemble_Call {
	return &MockAssembler_Assemble_Call{Call: _e.mock.On("Assemble", ctx, input)}
}

func (_c *MockAssembler_Assemble_Call) Run(run func(ctx context.Context, input output.AssembleInput)) *MockAssembler_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(output.AssembleInput))
	})
	return _c
}

func (_c *MockAssembler_Assemble_Call) Return(_a0 *output.AssembleResult, _a1 error) *MockAssembler_Assemble_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAssembler_Assemble_Call) RunAndReturn(run func(context.Context, output.AssembleInput) (*output.AssembleResult, error)) *MockAssembler_Assemble_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: ctx, outputPath
func (_m *MockAssembler) Validate(ctx context.Context, outputPath string) error {
	ret := _m.Called(ctx, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, outputPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAssembler_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockAssembler_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - outputPath string
func (_e *MockAssembler_Expecter) Validate(ctx interface{}, outputPath interface{}) *MockAssembler_Validate_Call {
	return &MockAssembler_Validate_Call{Call: _e.mock.On("Validate", ctx, outputPath)}
}

func (_c *MockAssembler_Validate_Call) Run(run func(ctx context.Context, outputPath string)) *MockAssembler_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAssembler_Validate_Call) Return(_a0 error) *MockAssembler_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAssembler_Validate_Call) RunAndReturn(run func(context.Context, string) error) *MockAssembler_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssembler creates a new instance of MockAssembler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssembler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssembler {
	mock := &MockAssembler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
