// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/sushistack/yt.pipe/internal/domain"
	llm "github.com/sushistack/yt.pipe/internal/plugin/llm"

	mock "github.com/stretchr/testify/mock"
)

// MockLLM is an autogenerated mock type for the LLM type
type MockLLM struct {
	mock.Mock
}

type MockLLM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLM) EXPECT() *MockLLM_Expecter {
	return &MockLLM_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, messages, opts
func (_m *MockLLM) Complete(ctx context.Context, messages []llm.Message, opts llm.CompletionOptions) (*llm.CompletionResult, error) {
	ret := _m.Called(ctx, messages, opts)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *llm.CompletionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []llm.Message, llm.CompletionOptions) (*llm.CompletionResult, error)); ok {
		return rf(ctx, messages, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []llm.Message, llm.CompletionOptions) *llm.CompletionResult); ok {
		r0 = rf(ctx, messages, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llm.CompletionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []llm.Message, llm.CompletionOptions) error); ok {
		r1 = rf(ctx, messages, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLM_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockLLM_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []llm.Message
//   - opts llm.CompletionOptions
func (_e *MockLLM_Expecter) Complete(ctx interface{}, messages interface{}, opts interface{}) *MockLLM_Complete_Call {
	return &MockLLM_Complete_Call{Call: _e.mock.On("Complete", ctx, messages, opts)}
}

func (_c *MockLLM_Complete_Call) Run(run func(ctx context.Context, messages []llm.Message, opts llm.CompletionOptions)) *MockLLM_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]llm.Message), args[2].(llm.CompletionOptions))
	})
	return _c
}

func (_c *MockLLM_Complete_Call) Return(_a0 *llm.CompletionResult, _a1 error) *MockLLM_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLM_Complete_Call) RunAndReturn(run func(context.Context, []llm.Message, llm.CompletionOptions) (*llm.CompletionResult, error)) *MockLLM_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWithVision provides a mock function with given fields: ctx, messages, opts
func (_m *MockLLM) CompleteWithVision(ctx context.Context, messages []llm.VisionMessage, opts llm.CompletionOptions) (*llm.CompletionResult, error) {
	ret := _m.Called(ctx, messages, opts)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWithVision")
	}

	var r0 *llm.CompletionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []llm.VisionMessage, llm.CompletionOptions) (*llm.CompletionResult, error)); ok {
		return rf(ctx, messages, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []llm.VisionMessage, llm.CompletionOptions) *llm.CompletionResult); ok {
		r0 = rf(ctx, messages, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llm.CompletionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []llm.VisionMessage, llm.CompletionOptions) error); ok {
		r1 = rf(ctx, messages, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateScenario provides a mock function with given fields: ctx, scpID, mainText, facts, metadata
func (_m *MockLLM) GenerateScenario(ctx context.Context, scpID string, mainText string, facts []domain.FactTag, metadata map[string]string) (*domain.ScenarioOutput, error) {
	ret := _m.Called(ctx, scpID, mainText, facts, metadata)

	if len(ret) == 0 {
		panic("no return value specified for GenerateScenario")
	}

	var r0 *domain.ScenarioOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []domain.FactTag, map[string]string) (*domain.ScenarioOutput, error)); ok {
		return rf(ctx, scpID, mainText, facts, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []domain.FactTag, map[string]string) *domain.ScenarioOutput); ok {
		r0 = rf(ctx, scpID, mainText, facts, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ScenarioOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []domain.FactTag, map[string]string) error); ok {
		r1 = rf(ctx, scpID, mainText, facts, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLM_GenerateScenario_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateScenario'
type MockLLM_GenerateScenario_Call struct {
	*mock.Call
}

// GenerateScenario is a helper method to define mock.On call
//   - ctx context.Context
//   - scpID string
//   - mainText string
//   - facts []domain.FactTag
//   - metadata map[string]string
func (_e *MockLLM_Expecter) GenerateScenario(ctx interface{}, scpID interface{}, mainText interface{}, facts interface{}, metadata interface{}) *MockLLM_GenerateScenario_Call {
	return &MockLLM_GenerateScenario_Call{Call: _e.mock.On("GenerateScenario", ctx, scpID, mainText, facts, metadata)}
}

func (_c *MockLLM_GenerateScenario_Call) Run(run func(ctx context.Context, scpID string, mainText string, facts []domain.FactTag, metadata map[string]string)) *MockLLM_GenerateScenario_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]domain.FactTag), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockLLM_GenerateScenario_Call) Return(_a0 *domain.ScenarioOutput, _a1 error) *MockLLM_GenerateScenario_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLM_GenerateScenario_Call) RunAndReturn(run func(context.Context, string, string, []domain.FactTag, map[string]string) (*domain.ScenarioOutput, error)) *MockLLM_GenerateScenario_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateSection provides a mock function with given fields: ctx, scenario, sceneNum, instruction
func (_m *MockLLM) RegenerateSection(ctx context.Context, scenario *domain.ScenarioOutput, sceneNum int, instruction string) (*domain.SceneScript, error) {
	ret := _m.Called(ctx, scenario, sceneNum, instruction)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateSection")
	}

	var r0 *domain.SceneScript
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ScenarioOutput, int, string) (*domain.SceneScript, error)); ok {
		return rf(ctx, scenario, sceneNum, instruction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ScenarioOutput, int, string) *domain.SceneScript); ok {
		r0 = rf(ctx, scenario, sceneNum, instruction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SceneScript)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ScenarioOutput, int, string) error); ok {
		r1 = rf(ctx, scenario, sceneNum, instruction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLM_RegenerateSection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateSection'
type MockLLM_RegenerateSection_Call struct {
	*mock.Call
}

// RegenerateSection is a helper method to define mock.On call
//   - ctx context.Context
//   - scenario *domain.ScenarioOutput
//   - sceneNum int
//   - instruction string
func (_e *MockLLM_Expecter) RegenerateSection(ctx interface{}, scenario interface{}, sceneNum interface{}, instruction interface{}) *MockLLM_RegenerateSection_Call {
	return &MockLLM_RegenerateSection_Call{Call: _e.mock.On("RegenerateSection", ctx, scenario, sceneNum, instruction)}
}

func (_c *MockLLM_RegenerateSection_Call) Run(run func(ctx context.Context, scenario *domain.ScenarioOutput, sceneNum int, instruction string)) *MockLLM_RegenerateSection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ScenarioOutput), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockLLM_RegenerateSection_Call) Return(_a0 *domain.SceneScript, _a1 error) *MockLLM_RegenerateSection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLM_RegenerateSection_Call) RunAndReturn(run func(context.Context, *domain.ScenarioOutput, int, string) (*domain.SceneScript, error)) *MockLLM_RegenerateSection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLM creates a new instance of MockLLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLM {
	mock := &MockLLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
