with-expecter: true
dir: "internal/mocks"
outpkg: "mocks"
packages:
  github.com/sushistack/yt.pipe/internal/plugin/llm:
    interfaces:
      LLM:
  github.com/sushistack/yt.pipe/internal/plugin/tts:
    interfaces:
      TTS:
  github.com/sushistack/yt.pipe/internal/plugin/imagegen:
    interfaces:
      ImageGen:
  github.com/sushistack/yt.pipe/internal/plugin/output:
    interfaces:
      Assembler:
