package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sushistack/yt.pipe/internal/config"
	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// newTestInitCmd builds a *cobra.Command with the same flags registered in
// the real initCmd.init() function, so tests can exercise runWizardNonInteractive
// without touching the global cobra command tree.
func newTestInitCmd() *cobra.Command {
	cmd := &cobra.Command{Use: "init"}
	cmd.Flags().Bool("force", false, "")
	cmd.Flags().Bool("non-interactive", false, "")
	cmd.Flags().String("scp-data-path", "", "")
	cmd.Flags().String("workspace-path", "", "")
	cmd.Flags().String("llm-api-key", "", "")
	cmd.Flags().String("imagegen-api-key", "", "")
	cmd.Flags().String("tts-provider", "", "")
	cmd.Flags().String("tts-api-key", "", "")
	return cmd
}

func TestGenerateConfig_CreatesDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configDir := filepath.Join(tmpDir, "newdir", "nested")

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "openai",
		OutputProvider:   "capcut",
	}

	err := generateConfig(result, configDir)
	require.NoError(t, err)

	// Verify directory was created with 0700 permissions
	info, statErr := os.Stat(configDir)
	require.NoError(t, statErr)
	assert.True(t, info.IsDir())
	assert.Equal(t, os.FileMode(0700), info.Mode().Perm())
}

func TestGenerateConfig_WritesValidYAML(t *testing.T) {
	configDir := t.TempDir()

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		LLMAPIKey:        "sk-test-key-12345",
		ImageGenProvider: "siliconflow",
		ImageGenAPIKey:   "sf-test-key-67890",
		TTSProvider:      "google",
		TTSAPIKey:        "gcp-test-key",
		OutputProvider:   "capcut",
	}

	err := generateConfig(result, configDir)
	require.NoError(t, err)

	content, readErr := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	require.NoError(t, readErr)

	text := string(content)

	// Check key lines are present
	assert.Contains(t, text, `scp_data_path: "/data/scp"`)
	assert.Contains(t, text, `workspace_path: "/data/workspace"`)
	assert.Contains(t, text, `provider: "openai"`)
	assert.Contains(t, text, `provider: "siliconflow"`)
	assert.Contains(t, text, `provider: "google"`)
	assert.Contains(t, text, `provider: "capcut"`)
	assert.Contains(t, text, "# Generated by yt-pipe init on")
	assert.Contains(t, text, "# Configuration Priority")
}

func TestGenerateConfig_NoPlaintextKeys(t *testing.T) {
	configDir := t.TempDir()

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		LLMAPIKey:        "sk-super-secret-llm-key",
		ImageGenProvider: "siliconflow",
		ImageGenAPIKey:   "sf-super-secret-img-key",
		TTSProvider:      "openai",
		TTSAPIKey:        "sk-super-secret-tts-key",
		OutputProvider:   "capcut",
	}

	err := generateConfig(result, configDir)
	require.NoError(t, err)

	content, readErr := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	require.NoError(t, readErr)

	text := string(content)

	// API keys must NOT appear as values in the generated config
	assert.NotContains(t, text, "sk-super-secret-llm-key")
	assert.NotContains(t, text, "sf-super-secret-img-key")
	assert.NotContains(t, text, "sk-super-secret-tts-key")

	// But env var instructions should be present
	assert.Contains(t, text, "YTP_LLM_API_KEY")
	assert.Contains(t, text, "YTP_IMAGEGEN_API_KEY")
	assert.Contains(t, text, "YTP_TTS_API_KEY")
}

func TestGenerateConfig_ForceOverwrite(t *testing.T) {
	configDir := t.TempDir()
	configPath := filepath.Join(configDir, "config.yaml")

	// Write initial config
	err := os.WriteFile(configPath, []byte("old content"), 0600)
	require.NoError(t, err)

	result := &wizardResult{
		SCPDataPath:      "/new/path",
		WorkspacePath:    "/new/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "edge",
		OutputProvider:   "capcut",
	}

	// generateConfig always overwrites (force check is done before calling it)
	err = generateConfig(result, configDir)
	require.NoError(t, err)

	content, readErr := os.ReadFile(configPath)
	require.NoError(t, readErr)

	text := string(content)
	assert.NotContains(t, text, "old content")
	assert.Contains(t, text, `/new/path`)
	assert.Contains(t, text, `provider: "edge"`)
	// Edge TTS should not have API key instructions
	assert.Contains(t, text, "Edge TTS requires no API key")
}

func TestGenerateConfig_EdgeTTSNoAPIKeyComment(t *testing.T) {
	configDir := t.TempDir()

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "edge",
		OutputProvider:   "capcut",
	}

	err := generateConfig(result, configDir)
	require.NoError(t, err)

	content, readErr := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	require.NoError(t, readErr)

	text := string(content)
	assert.Contains(t, text, "Edge TTS requires no API key")
	assert.NotContains(t, text, "YTP_TTS_API_KEY")
}

func TestWizard_FullFlow(t *testing.T) {
	// Create temp dirs for path validation
	tmpDir := t.TempDir()
	scpDir := filepath.Join(tmpDir, "scp-data")
	workDir := filepath.Join(tmpDir, "workspace")

	// Simulate user input:
	// 1. Overwrite prompt won't appear (no existing config in this test path)
	// 2. SCP data path (doesn't exist, will be asked to create)
	// 3. Confirm create SCP dir -> y
	// 4. Workspace path (doesn't exist, will be asked to create)
	// 5. Confirm create workspace dir -> y
	// 6. LLM API key
	// 7. Skip validation -> y
	// 8. ImageGen API key
	// 9. Skip validation -> y
	// 10. TTS provider selection -> 1 (openai)
	// 11. TTS API key
	// 12. Skip validation -> y
	input := strings.Join([]string{
		scpDir,          // SCP data path
		"y",             // create dir
		workDir,         // workspace path
		"y",             // create dir
		"sk-test-llm",   // LLM API key
		"y",             // skip validation
		"sf-test-img",   // ImageGen API key
		"y",             // skip validation
		"1",             // TTS provider: openai
		"sk-test-tts",   // TTS API key
		"y",             // skip validation
	}, "\n")
	input += "\n"

	r := strings.NewReader(input)
	w := &bytes.Buffer{}

	// Override config dir to temp
	origDefaultConfigDir := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) {
		return filepath.Join(tmpDir, ".yt-pipe"), nil
	}
	defer func() { defaultConfigDirFn = origDefaultConfigDir }()

	err := runWizard(r, w, true)
	require.NoError(t, err)

	output := w.String()

	// Verify wizard output contains expected sections
	assert.Contains(t, output, "Setup Wizard")
	assert.Contains(t, output, "LLM Plugin")
	assert.Contains(t, output, "Image Generation Plugin")
	assert.Contains(t, output, "TTS Plugin")
	assert.Contains(t, output, "Output Assembler")
	assert.Contains(t, output, "Setup Summary")
	assert.Contains(t, output, "Next Steps")

	// Verify directories were created
	_, err = os.Stat(scpDir)
	assert.NoError(t, err)
	_, err = os.Stat(workDir)
	assert.NoError(t, err)

	// Verify config file was generated
	configPath := filepath.Join(tmpDir, ".yt-pipe", "config.yaml")
	content, readErr := os.ReadFile(configPath)
	require.NoError(t, readErr)

	text := string(content)
	assert.Contains(t, text, scpDir)
	assert.Contains(t, text, workDir)

	// API keys must NOT be in config file
	assert.NotContains(t, text, "sk-test-llm")
	assert.NotContains(t, text, "sf-test-img")
	assert.NotContains(t, text, "sk-test-tts")
}

func TestWizard_ExistingConfigNoForce(t *testing.T) {
	tmpDir := t.TempDir()
	configDir := filepath.Join(tmpDir, ".yt-pipe")
	require.NoError(t, os.MkdirAll(configDir, 0700))
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "config.yaml"), []byte("existing"), 0600))

	// User says "n" to overwrite
	r := strings.NewReader("n\n")
	w := &bytes.Buffer{}

	origDefaultConfigDir := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) {
		return configDir, nil
	}
	defer func() { defaultConfigDirFn = origDefaultConfigDir }()

	err := runWizard(r, w, false)
	require.NoError(t, err)
	assert.Contains(t, w.String(), "Aborted")

	// Original file should be unchanged
	content, _ := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	assert.Equal(t, "existing", string(content))
}

func TestDisplaySummary_MasksKeys(t *testing.T) {
	w := &bytes.Buffer{}

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		LLMAPIKey:        "sk-proj-1234567890abcdef",
		ImageGenProvider: "siliconflow",
		ImageGenAPIKey:   "sf-abcdefghijklmnop",
		TTSProvider:      "openai",
		TTSAPIKey:        "sk-tts-key-secret",
		OutputProvider:   "capcut",
	}

	displaySummary(w, result, "/home/test/.yt-pipe/config.yaml")

	output := w.String()

	// Keys should be masked (first 4 chars + "****")
	assert.Contains(t, output, "sk-p****")
	assert.Contains(t, output, "sf-a****")
	assert.Contains(t, output, "sk-t****")

	// Full keys must NEVER appear in output (security: no plaintext keys)
	assert.NotContains(t, output, "sk-proj-1234567890abcdef")
	assert.NotContains(t, output, "sf-abcdefghijklmnop")
	assert.NotContains(t, output, "sk-tts-key-secret")

	// Next steps
	assert.Contains(t, output, "yt-pipe config validate")
	assert.Contains(t, output, "yt-pipe config show")
}

func TestDisplaySummary_NoKeys(t *testing.T) {
	w := &bytes.Buffer{}

	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "edge",
		OutputProvider:   "capcut",
	}

	displaySummary(w, result, "/home/test/.yt-pipe/config.yaml")

	output := w.String()

	assert.Contains(t, output, "(not set)")
	// Edge TTS should not suggest TTS key export
	assert.NotContains(t, output, "YTP_TTS_API_KEY")
}

func TestMaskKey(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"", "(not set)"},
		{"ab", "****"},
		{"abcd", "****"},
		{"abcde", "abcd****"},
		{"sk-proj-1234567890", "sk-p****"},
	}

	for _, tc := range tests {
		assert.Equal(t, tc.expected, maskKey(tc.input))
	}
}

func TestValidateOrCreateDir_ExistingDir(t *testing.T) {
	dir := t.TempDir()
	r := strings.NewReader("")
	w := &bytes.Buffer{}

	err := validateOrCreateDir(r, w, dir)
	assert.NoError(t, err)
}

func TestValidateOrCreateDir_CreatesDir(t *testing.T) {
	tmpDir := t.TempDir()
	newDir := filepath.Join(tmpDir, "newdir")

	r := strings.NewReader("y\n")
	w := &bytes.Buffer{}

	err := validateOrCreateDir(r, w, newDir)
	require.NoError(t, err)

	info, statErr := os.Stat(newDir)
	require.NoError(t, statErr)
	assert.True(t, info.IsDir())
	assert.Contains(t, w.String(), "Created")
}

func TestValidateOrCreateDir_DeclineCreate(t *testing.T) {
	tmpDir := t.TempDir()
	newDir := filepath.Join(tmpDir, "newdir")

	r := strings.NewReader("n\n")
	w := &bytes.Buffer{}

	err := validateOrCreateDir(r, w, newDir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "does not exist")
}

func TestValidateOrCreateDir_NotADirectory(t *testing.T) {
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "afile")
	require.NoError(t, os.WriteFile(filePath, []byte("x"), 0600))

	r := strings.NewReader("")
	w := &bytes.Buffer{}

	err := validateOrCreateDir(r, w, filePath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not a directory")
}

// ---------------------------------------------------------------------------
// Non-interactive mode tests
// ---------------------------------------------------------------------------

func TestInitNonInteractive_BasicFlow(t *testing.T) {
	tmpDir := t.TempDir()
	scpDir := filepath.Join(tmpDir, "scp")
	workDir := filepath.Join(tmpDir, "work")

	origFn := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) { return filepath.Join(tmpDir, ".yt-pipe"), nil }
	defer func() { defaultConfigDirFn = origFn }()

	cmd := newTestInitCmd()
	require.NoError(t, cmd.Flags().Set("scp-data-path", scpDir))
	require.NoError(t, cmd.Flags().Set("workspace-path", workDir))
	require.NoError(t, cmd.Flags().Set("llm-api-key", "sk-test-llm"))
	require.NoError(t, cmd.Flags().Set("imagegen-api-key", "sf-test-img"))
	require.NoError(t, cmd.Flags().Set("tts-provider", "google"))
	require.NoError(t, cmd.Flags().Set("tts-api-key", "gcp-test-tts"))

	err := runWizardNonInteractive(cmd, false)
	require.NoError(t, err)

	// Directories should have been created
	_, statErr := os.Stat(scpDir)
	assert.NoError(t, statErr)
	_, statErr = os.Stat(workDir)
	assert.NoError(t, statErr)

	// Config file should exist and contain expected provider values
	configPath := filepath.Join(tmpDir, ".yt-pipe", "config.yaml")
	content, readErr := os.ReadFile(configPath)
	require.NoError(t, readErr)
	text := string(content)

	assert.Contains(t, text, `provider: "openai"`)      // LLM default
	assert.Contains(t, text, `provider: "siliconflow"`) // ImageGen default
	assert.Contains(t, text, `provider: "google"`)      // TTS as set
	assert.Contains(t, text, `provider: "capcut"`)      // Output default
	assert.Contains(t, text, scpDir)
	assert.Contains(t, text, workDir)

	// API keys must NOT be stored as plaintext
	assert.NotContains(t, text, "sk-test-llm")
	assert.NotContains(t, text, "sf-test-img")
	assert.NotContains(t, text, "gcp-test-tts")
}

func TestInitNonInteractive_DefaultProviders(t *testing.T) {
	tmpDir := t.TempDir()

	origFn := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) { return filepath.Join(tmpDir, ".yt-pipe"), nil }
	defer func() { defaultConfigDirFn = origFn }()

	// No flags set – everything uses built-in defaults
	cmd := newTestInitCmd()

	err := runWizardNonInteractive(cmd, false)
	require.NoError(t, err)

	configPath := filepath.Join(tmpDir, ".yt-pipe", "config.yaml")
	content, readErr := os.ReadFile(configPath)
	require.NoError(t, readErr)
	text := string(content)

	// Provider defaults
	assert.Contains(t, text, `provider: "openai"`)      // LLM + TTS
	assert.Contains(t, text, `provider: "siliconflow"`) // ImageGen
	assert.Contains(t, text, `provider: "capcut"`)      // Output
}

func TestInitNonInteractive_ExistingConfigNoForce(t *testing.T) {
	tmpDir := t.TempDir()
	configDir := filepath.Join(tmpDir, ".yt-pipe")
	require.NoError(t, os.MkdirAll(configDir, 0700))
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "config.yaml"), []byte("existing"), 0600))

	origFn := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) { return configDir, nil }
	defer func() { defaultConfigDirFn = origFn }()

	cmd := newTestInitCmd()

	err := runWizardNonInteractive(cmd, false /* force=false */)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "config already exists")
	assert.Contains(t, err.Error(), "--force")

	// Original file must be unchanged
	content, _ := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	assert.Equal(t, "existing", string(content))
}

func TestInitNonInteractive_ForceOverwrite(t *testing.T) {
	tmpDir := t.TempDir()
	configDir := filepath.Join(tmpDir, ".yt-pipe")
	require.NoError(t, os.MkdirAll(configDir, 0700))
	require.NoError(t, os.WriteFile(filepath.Join(configDir, "config.yaml"), []byte("old content"), 0600))

	origFn := defaultConfigDirFn
	defaultConfigDirFn = func() (string, error) { return configDir, nil }
	defer func() { defaultConfigDirFn = origFn }()

	cmd := newTestInitCmd()
	require.NoError(t, cmd.Flags().Set("tts-provider", "edge"))

	err := runWizardNonInteractive(cmd, true /* force=true */)
	require.NoError(t, err)

	content, readErr := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	require.NoError(t, readErr)
	text := string(content)

	assert.NotContains(t, text, "old content")
	assert.Contains(t, text, `provider: "edge"`)
	assert.Contains(t, text, "Edge TTS requires no API key")
}

// ---------------------------------------------------------------------------
// Plugin swap integration tests (AC #4)
// ---------------------------------------------------------------------------

func TestPluginSwap_ImageGenProvider(t *testing.T) {
	configDir := t.TempDir()

	// 1. Generate config with siliconflow as imagegen provider
	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "openai",
		OutputProvider:   "capcut",
	}
	err := generateConfig(result, configDir)
	require.NoError(t, err)

	configPath := filepath.Join(configDir, "config.yaml")

	// 2. Read the generated file
	content, err := os.ReadFile(configPath)
	require.NoError(t, err)

	// 3. Replace "siliconflow" with "dall-e"
	original := string(content)
	modified := strings.ReplaceAll(original, `"siliconflow"`, `"dall-e"`)
	require.NotEqual(t, original, modified, "replacement should have changed the content")

	// 4. Write modified file back
	err = os.WriteFile(configPath, []byte(modified), 0600)
	require.NoError(t, err)

	// 5. Load with config.Load using explicit path
	loaded, err := config.Load(configPath)
	require.NoError(t, err)

	// 6. Assert the new provider is recognized
	assert.Equal(t, "dall-e", loaded.Config.ImageGen.Provider)
}

func TestPluginSwap_TTSProvider(t *testing.T) {
	configDir := t.TempDir()

	// 1. Generate config with openai as TTS provider
	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "openai",
		OutputProvider:   "capcut",
	}
	err := generateConfig(result, configDir)
	require.NoError(t, err)

	configPath := filepath.Join(configDir, "config.yaml")

	// 2. Read the generated file
	content, err := os.ReadFile(configPath)
	require.NoError(t, err)

	// 3. Replace tts provider "openai" with "edge"
	// Target the specific tts block line to avoid touching the llm provider value
	original := string(content)
	modified := strings.Replace(original, "tts:\n  provider: \"openai\"", "tts:\n  provider: \"edge\"", 1)
	require.NotEqual(t, original, modified, "replacement should have changed the content")

	// 4. Write modified file back
	err = os.WriteFile(configPath, []byte(modified), 0600)
	require.NoError(t, err)

	// 5. Load with config.Load using explicit path
	loaded, err := config.Load(configPath)
	require.NoError(t, err)

	// 6. Assert the new TTS provider is recognized
	assert.Equal(t, "edge", loaded.Config.TTS.Provider)
	// LLM provider should remain openai
	assert.Equal(t, "openai", loaded.Config.LLM.Provider)
}

func TestPluginSwap_ConfigReload(t *testing.T) {
	configDir := t.TempDir()

	// Generate config with initial providers
	result := &wizardResult{
		SCPDataPath:      "/data/scp",
		WorkspacePath:    "/data/workspace",
		LLMProvider:      "openai",
		ImageGenProvider: "siliconflow",
		TTSProvider:      "openai",
		OutputProvider:   "capcut",
	}
	err := generateConfig(result, configDir)
	require.NoError(t, err)

	configPath := filepath.Join(configDir, "config.yaml")

	// Read generated file
	content, err := os.ReadFile(configPath)
	require.NoError(t, err)
	original := string(content)

	// Modify imagegen provider: siliconflow -> stable-diffusion
	modified := strings.ReplaceAll(original, `"siliconflow"`, `"stable-diffusion"`)
	// Modify TTS provider: openai -> google (within tts block only)
	modified = strings.Replace(modified, "tts:\n  provider: \"openai\"", "tts:\n  provider: \"google\"", 1)
	require.NotEqual(t, original, modified, "both replacements should have changed the content")

	// Write modified file back
	err = os.WriteFile(configPath, []byte(modified), 0600)
	require.NoError(t, err)

	// Reload config with explicit path
	loaded, err := config.Load(configPath)
	require.NoError(t, err)

	// Assert both new providers are recognized
	assert.Equal(t, "stable-diffusion", loaded.Config.ImageGen.Provider)
	assert.Equal(t, "google", loaded.Config.TTS.Provider)
	// LLM provider should be unchanged
	assert.Equal(t, "openai", loaded.Config.LLM.Provider)
}
