// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tts "github.com/sushistack/yt.pipe/internal/plugin/tts"
)

// MockTTS is an autogenerated mock type for the TTS type
type MockTTS struct {
	mock.Mock
}

type MockTTS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTTS) EXPECT() *MockTTS_Expecter {
	return &MockTTS_Expecter{mock: &_m.Mock}
}

// Synthesize provides a mock function with given fields: ctx, text, voice, opts
func (_m *MockTTS) Synthesize(ctx context.Context, text string, voice string, opts *tts.TTSOptions) (*tts.SynthesisResult, error) {
	ret := _m.Called(ctx, text, voice, opts)

	if len(ret) == 0 {
		panic("no return value specified for Synthesize")
	}

	var r0 *tts.SynthesisResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *tts.TTSOptions) (*tts.SynthesisResult, error)); ok {
		return rf(ctx, text, voice, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *tts.TTSOptions) *tts.SynthesisResult); ok {
		r0 = rf(ctx, text, voice, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tts.SynthesisResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *tts.TTSOptions) error); ok {
		r1 = rf(ctx, text, voice, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTTS_Synthesize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synthesize'
type MockTTS_Synthesize_Call struct {
	*mock.Call
}

// Synthesize is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - voice string
//   - opts *tts.TTSOptions
func (_e *MockTTS_Expecter) Synthesize(ctx interface{}, text interface{}, voice interface{}, opts interface{}) *MockTTS_Synthesize_Call {
	return &MockTTS_Synthesize_Call{Call: _e.mock.On("Synthesize", ctx, text, voice, opts)}
}

func (_c *MockTTS_Synthesize_Call) Run(run func(ctx context.Context, text string, voice string, opts *tts.TTSOptions)) *MockTTS_Synthesize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*tts.TTSOptions))
	})
	return _c
}

func (_c *MockTTS_Synthesize_Call) Return(_a0 *tts.SynthesisResult, _a1 error) *MockTTS_Synthesize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTTS_Synthesize_Call) RunAndReturn(run func(context.Context, string, string, *tts.TTSOptions) (*tts.SynthesisResult, error)) *MockTTS_Synthesize_Call {
	_c.Call.Return(run)
	return _c
}

// SynthesizeWithOverrides provides a mock function with given fields: ctx, text, voice, overrides, opts
func (_m *MockTTS) SynthesizeWithOverrides(ctx context.Context, text string, voice string, overrides map[string]string, opts *tts.TTSOptions) (*tts.SynthesisResult, error) {
	ret := _m.Called(ctx, text, voice, overrides, opts)

	if len(ret) == 0 {
		panic("no return value specified for SynthesizeWithOverrides")
	}

	var r0 *tts.SynthesisResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, *tts.TTSOptions) (*tts.SynthesisResult, error)); ok {
		return rf(ctx, text, voice, overrides, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, *tts.TTSOptions) *tts.SynthesisResult); ok {
		r0 = rf(ctx, text, voice, overrides, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tts.SynthesisResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]string, *tts.TTSOptions) error); ok {
		r1 = rf(ctx, text, voice, overrides, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTTS_SynthesizeWithOverrides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SynthesizeWithOverrides'
type MockTTS_SynthesizeWithOverrides_Call struct {
	*mock.Call
}

// SynthesizeWithOverrides is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - voice string
//   - overrides map[string]string
//   - opts *tts.TTSOptions
func (_e *MockTTS_Expecter) SynthesizeWithOverrides(ctx interface{}, text interface{}, voice interface{}, overrides interface{}, opts interface{}) *MockTTS_SynthesizeWithOverrides_Call {
	return &MockTTS_SynthesizeWithOverrides_Call{Call: _e.mock.On("SynthesizeWithOverrides", ctx, text, voice, overrides, opts)}
}

func (_c *MockTTS_SynthesizeWithOverrides_Call) Run(run func(ctx context.Context, text string, voice string, overrides map[string]string, opts *tts.TTSOptions)) *MockTTS_SynthesizeWithOverrides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string), args[4].(*tts.TTSOptions))
	})
	return _c
}

func (_c *MockTTS_SynthesizeWithOverrides_Call) Return(_a0 *tts.SynthesisResult, _a1 error) *MockTTS_SynthesizeWithOverrides_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTTS_SynthesizeWithOverrides_Call) RunAndReturn(run func(context.Context, string, string, map[string]string, *tts.TTSOptions) (*tts.SynthesisResult, error)) *MockTTS_SynthesizeWithOverrides_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTTS creates a new instance of MockTTS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTTS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTTS {
	mock := &MockTTS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
